[workspace]
members = [
    "./temu-window"
]

[package]
name = "temu"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
temu-window = { path = "./temu-window" }

bytemuck = { version = "1.7.2", features = ["derive"] }
crossbeam-utils = "0.8.5"
env_logger = "0.9.0"
fps_counter = "2.0.0"
futures-executor = "0.3.17"
futures-task = "0.3.17"
grid = "0.6.0"
log = "0.4.14"
parking_lot = "0.11.2"
termwiz = "0.13.0"
wgpu = { version = "0.11.0", features = ["spirv"] }

portable-pty = "0.5.0"
crossbeam-channel = "0.5.1"
lyon = "0.17.10"
rustybuzz = "0.4.0"
ttf-parser = "0.12"
ahash = "0.7.6"
rayon = "1.5.1"
arrayvec = "0.7.2"

[features]

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = "thin"
