[workspace]
members = [
    "./temu-window"
]

[package]
name = "temu"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
temu-window = { path = "./temu-window" }

bytemuck = "1.7.2"
crossbeam-utils = "0.8.5"
env_logger = "0.9.0"
fps_counter = "2.0.0"
futures-executor = "0.3.17"
futures-task = "0.3.17"
grid = "0.6.0"
log = "0.4.14"
parking_lot = "0.11.2"
termwiz = "0.13.0"
wgpu = "0.11.0"
wgpu_glyph = "0.15.1"

portable-pty = "0.5.0"
crossbeam-channel = "0.5.1"
ttf-parser = "0.13.2"
lyon = "0.17.10"

[features]

[profile.release]
lto = "thin"
