[package]
name = "temu"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
flume = "0.10.9"
pollster = "0.2.4"
raw-window-handle = "0.3.3"
wayland-client = { version = "0.29.1", default-features = false, features = ["use_system_lib"] }
wayland-egl = "0.29.1"
wayland-protocols = { version = "0.29.1", features = ["client", "unstable_protocols"] }
wgpu = "0.11.0"
wgpu_glyph = "0.15.1"

[features]
